# Generated by Django 3.1.2 on 2021-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度'),
            preserve_default=False,
        ),
    ]
